# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_xbar_1/top_xbar_1.xci
# IP: The module: 'top_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_xbar_1/top_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_xbar_1/top_xbar_1.xci
# IP: The module: 'top_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_xbar_1/top_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
