# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_ad9708_send_0_0/top_ad9708_send_0_0.xci
# IP: The module: 'top_ad9708_send_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_ad9708_send_0_0/src/dac_fifo/dac_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_fifo || ORIG_REF_NAME==dac_fifo} -quiet] -quiet

# XDC: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_ad9708_send_0_0/src/dac_fifo/dac_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dac_fifo || ORIG_REF_NAME==dac_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_ad9708_send_0_0/src/dac_fifo/dac_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dac_fifo || ORIG_REF_NAME==dac_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_ad9708_send_0_0/top_ad9708_send_0_0.xci
# IP: The module: 'top_ad9708_send_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_ad9708_send_0_0/src/dac_fifo/dac_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_fifo || ORIG_REF_NAME==dac_fifo} -quiet] -quiet

# XDC: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_ad9708_send_0_0/src/dac_fifo/dac_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dac_fifo || ORIG_REF_NAME==dac_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/zhengyuan/src/FPGA_Studio/10_ad9708_dma/dma_dac.srcs/sources_1/bd/top/ip/top_ad9708_send_0_0/src/dac_fifo/dac_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dac_fifo || ORIG_REF_NAME==dac_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
