# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ad9708.xdc

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_dma_0_0/top_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axi_dma_0_0 || ORIG_REF_NAME==top_axi_dma_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ps7_0_axi_periph_1/top_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_ps7_0_axi_periph_1 || ORIG_REF_NAME==top_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/top/ip/top_rst_clk_wiz_100M_0/top_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_100M_0 || ORIG_REF_NAME==top_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_interconnect_0_0/top_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axi_interconnect_0_0 || ORIG_REF_NAME==top_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ad9708_send_0_0/top_ad9708_send_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_ad9708_send_0_0 || ORIG_REF_NAME==top_ad9708_send_0_0} -quiet] -quiet

# IP: bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_0_0 || ORIG_REF_NAME==top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_0/top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xbar_0 || ORIG_REF_NAME==top_xbar_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_1/top_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xbar_1 || ORIG_REF_NAME==top_xbar_1} -quiet] -quiet

# IP: bd/top/ip/top_auto_us_0/top_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_us_0 || ORIG_REF_NAME==top_auto_us_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_1/top_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_pc_1 || ORIG_REF_NAME==top_auto_pc_1} -quiet] -quiet

# XDC: bd/top/top_ooc.xdc
